import { useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BarChart3, Check, CircleDollarSign, ImagePlus, Languages, LogOut, MapPin, Package, Pencil, Plus, Search, ShoppingBag, Star, Store, Trash2, Truck, Users, X } from 'lucide-react'
import { useStore } from '../context/useStore'
import { dateTime, money } from '../lib/format'

const emptyProduct = { name: '', category: 'Biscuits', price: '', stock: '', description: '', image: '' }
const DASHBOARD_DATE = new Date().toLocaleDateString('en-PK', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
const tabs = [{ id: 'overview', name: 'Overview', icon: BarChart3 }, { id: 'products', name: 'Products', icon: Package }, { id: 'orders', name: 'Orders', icon: ShoppingBag }, { id: 'customers', name: 'Customers', icon: Users }, { id: 'ratings', name: 'Ratings', icon: Star }, { id: 'complaints', name: 'Complaints', icon: Truck }, { id: 'offers', name: 'Offers', icon: Star }]

export default function OwnerDashboard() {
  const { products, orders, customers, offers, ratings, complaints, saveProduct, deleteProduct, saveOffer, updateOrderStatus, ownerSignIn, ownerSignOut, language, setLanguage, supabaseEnabled } = useStore()
  const [authenticated, setAuthenticated] = useState(sessionStorage.getItem('malik-owner-session') === '1')
  const [formError, setFormError] = useState('')
  const [tab, setTab] = useState('overview')
  const [search, setSearch] = useState('')
  const [editing, setEditing] = useState(null)
  const [saving, setSaving] = useState(false)
  const [offerModal, setOfferModal] = useState(false)
  const [notice, setNotice] = useState('')
  const [ownerQuery, setOwnerQuery] = useState('')
  const [status, setStatus] = useState('All orders')
  const cameraRef = useRef(null)
  const galleryRef = useRef(null)
  const revenue = orders.reduce((sum, order) => sum + Number(order.total || 0), 0)
  const visibleProducts = useMemo(() => products.filter((product) => `${product.name} ${product.category}`.toLowerCase().includes(search.toLowerCase())), [products, search])
  const visibleOrders = useMemo(() => orders.filter((order) => (status === 'All orders' || order.status === status) && `${order.customer_name || ''} ${order.shop_name || ''} ${order.phone || ''} ${order.id}`.toLowerCase().includes(ownerQuery.toLowerCase())), [orders, status, ownerQuery])
  async function signIn(event) { event.preventDefault(); const fields = new FormData(event.currentTarget); setFormError(''); try { await ownerSignIn(fields.get('username'), fields.get('password')); sessionStorage.setItem('malik-owner-session', '1'); setAuthenticated(true) } catch (error) { setFormError(error.message || 'Username or password is incorrect.') } }
  async function selectImage(file) { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { setFormError('Choose a JPG, PNG or WebP image under 5 MB.'); return } setFormError(''); const reader = new FileReader(); reader.onload = () => setEditing((item) => ({ ...item, image: reader.result })); reader.readAsDataURL(file) }
  async function submitProduct(event) { event.preventDefault(); setSaving(true); setNotice(''); try { await saveProduct(editing); setEditing(null); setNotice('Product saved and catalogue updated.') } catch (error) { setFormError(error.message || 'Product could not be saved.') } finally { setSaving(false) } }
  async function removeProduct(product) { if (!window.confirm(`Delete ${product.name}?`)) return; try { await deleteProduct(product.id); setNotice('Product removed.') } catch (error) { setNotice(error.message || 'Could not delete product.') } }
  async function submitOffer(event) { event.preventDefault(); const fields = new FormData(event.currentTarget); try { await saveOffer({ title: fields.get('title'), description: fields.get('description'), discount_percent: fields.get('discount_percent') }); setOfferModal(false); setNotice('Offer published to the customer storefront.') } catch (error) { setFormError(error.message || 'Offer could not be saved.') } }
  if (!authenticated) return <main className="owner-login-page"><Link to="/" className="brand-lockup"><span className="brand-mark">M<span>+</span></span><span className="brand-copy"><strong>MALIK ADREES</strong><small>SHOP & SUPPLY</small></span></Link><Link to="/" className="back-link"><ArrowLeft size={15} /> Return to storefront</Link><form className="owner-login-card" onSubmit={signIn}><div className="owner-login-mark"><Store size={23} /></div><span className="section-kicker">STORE MANAGEMENT</span><h1>Owner sign in</h1><p>Manage products, customer orders and shop offers.</p><label className="field-label">Username<input name="username" autoComplete="username" required placeholder="Owner username" /></label><label className="field-label">Password<input name="password" type="password" autoComplete="current-password" required placeholder="Password" /></label>{formError && <p className="form-error">{formError}</p>}<button className="button button--dark register-submit">Sign in <ArrowRight size={17} /></button><small className="form-hint">Demo credentials are set up as requested. Replace this client-side check with Supabase Auth before deployment.</small></form></main>
    return <main className="owner-login-page"><Link to="/" className="brand-lockup"><span className="brand-mark">M<span>+</span></span><span className="brand-copy"><strong>MALIK ADREES</strong><small>SHOP & SUPPLY</small></span></Link><Link to="/" className="back-link"><ArrowLeft size={15} /> Return to storefront</Link><form className="owner-login-card" onSubmit={signIn}><div className="owner-login-mark"><Store size={23} /></div><span className="section-kicker">STORE MANAGEMENT</span><h1>Owner sign in</h1><p>Manage products, customer orders and shop offers.</p><label className="field-label">Username<input name="username" autoComplete="username" required placeholder="Owner username" /></label><label className="field-label">Password<input name="password" type="password" autoComplete="current-password" required placeholder="Password" /></label>{formError && <p className="form-error">{formError}</p>}<button className="button button--dark register-submit">Sign in <ArrowRight size={17} /></button><small className="form-hint">{supabaseEnabled ? 'Use the owner Auth account configured for this store.' : 'Development preview only: username Ayan, password 000467. Not accepted in production.'}</small></form></main>
  return <main className="dashboard-shell"><aside className="dashboard-sidebar"><Link to="/" className="brand-lockup"><span className="brand-mark">M<span>+</span></span><span className="brand-copy"><strong>MALIK ADREES</strong><small>OWNER DESK</small></span></Link><div className="sidebar-label">WORKSPACE</div><nav className="dashboard-nav">{tabs.map(({ id, name, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'active' : ''}><Icon size={17} />{name}{id === 'orders' && orders.length > 0 && <span className="nav-count">{orders.length}</span>}{id === 'complaints' && complaints.length > 0 && <span className="nav-count">{complaints.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="owner-profile"><span>MA</span><div><strong>Malik Adrees</strong><small>Store owner</small></div><span className="owner-online" /></div><button className="sidebar-logout" onClick={async () => { sessionStorage.removeItem('malik-owner-session'); await ownerSignOut(); setAuthenticated(false) }}><LogOut size={16} /> Sign out</button></div></aside>
    <section className="dashboard-main"><header className="dashboard-topbar"><div><span className="dashboard-date">{DASHBOARD_DATE}</span><span className="live-indicator">{supabaseEnabled ? 'LIVE SYNC ON' : 'PREVIEW MODE'}</span></div><div className="dashboard-top-actions"><button className="language-switch" onClick={() => setLanguage(language === 'ur' ? 'en' : 'اردو')}><Languages size={15} />{language === 'ur' ? 'English' : 'اردو'}</button><Link to="/" className="view-store-link"><Store size={16} /> View store <ArrowRight size={14} /></Link></div></header><div className="dashboard-content"><div className="dashboard-page-heading"><div><span className="section-kicker">MALIK ADREES · SAMUNDRI</span><h1>{tabs.find((item) => item.id === tab)?.name || 'Overview'}</h1><p>Good day. Here’s what’s happening with your shop.</p></div><button className="button button--dark" onClick={() => { setEditing({ ...emptyProduct }); setFormError('') }}><Plus size={17} /> Add product</button></div>{notice && <div className="dashboard-notice"><Check size={16} />{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}><X size={15} /></button></div>}
      {(tab === 'overview' || tab === 'insights') && <><div className="metric-grid"><article className="metric-card"><span className="metric-icon metric-icon--green"><CircleDollarSign size={19} /></span><small>Recorded sales</small><strong>{money(revenue)}</strong><span className="metric-caption">Across {orders.length} orders</span></article><article className="metric-card"><span className="metric-icon metric-icon--peach"><ShoppingBag size={19} /></span><small>Total orders</small><strong>{orders.length}</strong><span className="metric-caption">{orders.filter((order) => order.status === 'Received').length} need attention</span></article><article className="metric-card"><span className="metric-icon metric-icon--blue"><Users size={19} /></span><small>Shop customers</small><strong>{customers.length}</strong><span className="metric-caption">Registered accounts</span></article><article className="metric-card"><span className="metric-icon metric-icon--yellow"><Package size={19} /></span><small>Active products</small><strong>{products.length}</strong><span className="metric-caption">{products.filter((product) => Number(product.stock) < 10).length} low on stock</span></article></div><div className="dashboard-columns"><section className="dashboard-panel"><div className="panel-heading"><div><span className="section-kicker">LATEST ACTIVITY</span><h2>Recent orders</h2></div><button className="panel-link" onClick={() => setTab('orders')}>View all <ArrowRight size={14} /></button></div>{orders.slice(0, 5).map((order) => <div className="recent-order-row" key={order.id}><span className="recent-order-icon"><ShoppingBag size={16} /></span><div><strong>{order.customer_name || 'Shop customer'}</strong><small>{order.shop_name} · {dateTime(order.created_at)}</small></div><strong>{money(order.total)}</strong><span className="status-pill">{order.status}</span></div>)}{orders.length === 0 && <div className="panel-empty">Your new orders will appear here.</div>}</section><section className="dashboard-panel stock-panel"><div className="panel-heading"><div><span className="section-kicker">INVENTORY CHECK</span><h2>Stock watch</h2></div></div>{products.filter((product) => Number(product.stock) < 15).slice(0, 5).map((product) => <div className="stock-watch-row" key={product.id}><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.category}</small></span><span className={product.stock < 5 ? 'stock-qty stock-qty--low' : 'stock-qty'}>{product.stock} left</span></div>)}{products.every((product) => Number(product.stock) >= 15) && <div className="panel-empty">Stock looks healthy right now.</div>}</section></div></>}
      {tab === 'products' && <section className="dashboard-panel table-panel"><div className="panel-heading"><div><span className="section-kicker">CATALOGUE MANAGEMENT</span><h2>{products.length} products</h2></div><label className="dashboard-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search products" /></label></div><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>PRICE</th><th>STOCK</th><th>RATING</th><th></th></tr></thead><tbody>{visibleProducts.map((product) => <tr key={product.id}><td><span className="table-product"><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.description}</small></span></span></td><td>{product.category}</td><td>{money(product.price)}</td><td><span className={product.stock < 10 ? 'stock-qty stock-qty--low' : 'stock-qty'}>{product.stock}</span></td><td><span className="rating"><Star size={13} fill="currentColor" /> {Number(product.rating || 0).toFixed(1)}</span></td><td><div className="table-actions"><button aria-label="Edit product" onClick={() => { setEditing({ ...product }); setFormError('') }}><Pencil size={15} /></button><button aria-label="Delete product" onClick={() => removeProduct(product)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>{visibleProducts.length === 0 && <div className="panel-empty">No products match that search.</div>}</section>}
      {tab === 'orders' && <section className="dashboard-panel table-panel"><div className="panel-heading"><div><span className="section-kicker">CUSTOMER FULFILMENT</span><h2>{orders.length} orders</h2></div><div className="order-filters"><label className="dashboard-search"><Search size={16} /><input value={ownerQuery} onChange={(event) => setOwnerQuery(event.target.value)} placeholder="Customer or phone" /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All orders</option><option>Received</option><option>Preparing</option><option>Out for delivery</option><option>Delivered</option></select></div></div><div className="table-scroll"><table><thead><tr><th>ORDER / DATE</th><th>SHOP & CUSTOMER</th><th>ITEMS</th><th>TOTAL</th><th>DELIVERY LOCATION</th><th>STATUS</th></tr></thead><tbody>{visibleOrders.map((order) => <tr key={order.id}><td><strong>#{String(order.id).slice(-6)}</strong><small className="table-sub">{dateTime(order.created_at)}</small></td><td><strong>{order.shop_name || 'Shop'}</strong><small className="table-sub">{order.customer_name} · {order.phone}</small><small className="table-sub">{order.address}</small></td><td>{(order.items || order.order_items || []).map((item) => <div key={item.product_id || item.id}>{item.product_name || item.name} × {item.quantity}</div>)}</td><td>{money(order.total)}</td><td><span className="location-cell"><MapPin size={14} />{order.delivery_location || order.address || 'Not shared'}</span></td><td><select className="status-select" value={order.status || 'Received'} onChange={async (event) => { try { await updateOrderStatus(order.id, event.target.value); setNotice('Order status updated.') } catch (error) { setNotice(error.message || 'Could not update order status.') } }}><option>Received</option><option>Preparing</option><option>Out for delivery</option><option>Delivered</option></select></td></tr>)}</tbody></table></div>{orders.length === 0 && <div className="panel-empty">Orders will show here as customers check out.</div>}</section>}
      {tab === 'customers' && <section className="dashboard-panel table-panel"><div className="panel-heading"><div><span className="section-kicker">LOCAL SHOP NETWORK</span><h2>{customers.length} customers</h2></div><label className="dashboard-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find customer" /></label></div><div className="table-scroll"><table><thead><tr><th>NAME</th><th>SHOP</th><th>PHONE</th><th>ADDRESS</th><th>ORDERS</th></tr></thead><tbody>{customers.filter((person) => `${person.full_name} ${person.shop_name} ${person.phone}`.toLowerCase().includes(search.toLowerCase())).map((person) => <tr key={person.id}><td><strong>{person.full_name}</strong></td><td>{person.shop_name}</td><td>{person.phone}</td><td>{person.address}</td><td>{orders.filter((order) => order.customer_id === person.id || order.phone === person.phone).length}</td></tr>)}</tbody></table></div>{customers.length === 0 && <div className="panel-empty">New shop registrations appear here.</div>}</section>}
      {tab === 'ratings' && <section className="dashboard-panel offers-manager"><div className="panel-heading"><div><span className="section-kicker">CUSTOMER FEEDBACK</span><h2>Product ratings & reviews</h2></div><span className="order-count">{ratings.length} ratings</span></div>{ratings.map((rating) => <article className="offer-manager-row" key={rating.id}><span className="rating"><Star size={15} fill="currentColor" /> {rating.stars}</span><div><strong>{rating.products?.name || rating.product_name || products.find((item) => item.id === rating.product_id)?.name || 'Product'}</strong><p>{rating.review || 'Rating only'} · {rating.customers?.full_name || rating.customer_name || 'Shop customer'}</p></div><span>{dateTime(rating.created_at)}</span></article>)}{ratings.length === 0 && <div className="panel-empty">Customer ratings and reviews will appear here.</div>}</section>}
      {tab === 'complaints' && <section className="dashboard-panel offers-manager"><div className="panel-heading"><div><span className="section-kicker">CUSTOMER SUPPORT</span><h2>Complaints & requests</h2></div><span className="order-count">{complaints.length} received</span></div>{complaints.map((complaint) => <article className="offer-manager-row" key={complaint.id}><span className="order-icon"><Truck size={17} /></span><div><strong>{complaint.customers?.shop_name || complaint.shop_name || 'Shop customer'} · {complaint.customers?.full_name || complaint.customer_name}</strong><p>{complaint.message}</p><small className="table-sub">{complaint.customers?.phone || complaint.phone}</small></div><span>{dateTime(complaint.created_at)}</span></article>)}{complaints.length === 0 && <div className="panel-empty">Customer messages will appear here.</div>}</section>}
      {tab === 'offers' && <section className="dashboard-panel offers-manager"><div className="panel-heading"><div><span className="section-kicker">PROMOTIONS</span><h2>Offers & deals</h2></div><button className="button button--dark" onClick={() => setOfferModal(true)}><Plus size={16} /> Create offer</button></div>{offers.map((offer) => <article className="offer-manager-row" key={offer.id}><span className="offer-spark">✳</span><div><strong>{offer.title}</strong><p>{offer.description}</p></div><span>{offer.discount_percent ? `${offer.discount_percent}% discount` : 'Deal'}</span></article>)}{offers.length === 0 && <div className="panel-empty">Create a promotion to feature it on the customer storefront.</div>}</section>}
      <footer className="dashboard-footer"><span>Store operations · Samundri, Punjab</span><span>Product and order data {supabaseEnabled ? 'syncs with Supabase' : 'is saved in this browser'}</span></footer>
    </div></section>
    {editing && <div className="modal-backdrop"><form className="product-modal" onSubmit={submitProduct}><button type="button" className="modal-close icon-button" onClick={() => setEditing(null)}><X size={19} /></button><span className="section-kicker">CATALOGUE EDITOR</span><h2>{editing.id ? 'Edit product' : 'Add a product'}</h2><div className="image-upload-area">{editing.image ? <img src={editing.image} alt="Product preview" /> : <ImagePlus size={25} />}<span>{editing.image ? 'Product image ready' : 'Add a product photo'}</span><div className="upload-actions"><button type="button" onClick={() => cameraRef.current?.click()}><Plus size={14} /> Camera</button><button type="button" onClick={() => galleryRef.current?.click()}><ImagePlus size={14} /> Gallery</button></div><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={(event) => selectImage(event.target.files[0])} /><input ref={galleryRef} hidden type="file" accept="image/*" onChange={(event) => selectImage(event.target.files[0])} /></div><div className="product-form-grid"><label className="field-label">Product name<input required value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label className="field-label">Category<select value={editing.category} onChange={(event) => setEditing({ ...editing, category: event.target.value })}>{['Biscuits', 'Toffees', 'Snacks', 'Chips', 'Cold Drinks', 'Chocolates', 'Grocery', 'General Store'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field-label">Price (PKR)<input type="number" min="0" required value={editing.price} onChange={(event) => setEditing({ ...editing, price: event.target.value })} /></label><label className="field-label">Stock quantity<input type="number" min="0" required value={editing.stock} onChange={(event) => setEditing({ ...editing, stock: event.target.value })} /></label></div><label className="field-label">Description<textarea rows="3" value={editing.description} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label>{formError && <p className="form-error">{formError}</p>}<button className="button button--dark checkout-button" disabled={saving}>{saving ? 'Saving…' : 'Save product'} <Check size={16} /></button></form></div>}
    {offerModal && <div className="modal-backdrop"><form className="review-modal" onSubmit={submitOffer}><button type="button" className="modal-close icon-button" onClick={() => setOfferModal(false)}><X size={19} /></button><span className="section-kicker">CUSTOMER PROMOTION</span><h2>Create an offer</h2><label className="field-label">Offer title<input name="title" required placeholder="Weekend snack deal" /></label><label className="field-label">Description<textarea name="description" rows="3" required placeholder="What's included in this offer?" /></label><label className="field-label">Discount percent<input name="discount_percent" type="number" min="0" max="100" placeholder="Optional" /></label><button className="button button--dark checkout-button">Publish offer <ArrowRight size={16} /></button></form></div>}
  </main>
}
